// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.1
// source: shared/proto/chaingateway.proto

package chaingateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChainGatewayService_ConvertAddress_FullMethodName  = "/wallet.chaingateway.ChainGatewayService/ConvertAddress"
	ChainGatewayService_BuildUnsignedTx_FullMethodName = "/wallet.chaingateway.ChainGatewayService/BuildUnsignedTx"
	ChainGatewayService_SendTx_FullMethodName          = "/wallet.chaingateway.ChainGatewayService/SendTx"
)

// ChainGatewayServiceClient is the client API for ChainGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainGatewayServiceClient interface {
	ConvertAddress(ctx context.Context, in *ConvertAddressRequest, opts ...grpc.CallOption) (*ConvertAddressResponse, error)
	BuildUnsignedTx(ctx context.Context, in *BuildUnsignedTxRequest, opts ...grpc.CallOption) (*BuildUnsignedTxResponse, error)
	SendTx(ctx context.Context, in *SendTxRequest, opts ...grpc.CallOption) (*SendTxResponse, error)
}

type chainGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChainGatewayServiceClient(cc grpc.ClientConnInterface) ChainGatewayServiceClient {
	return &chainGatewayServiceClient{cc}
}

func (c *chainGatewayServiceClient) ConvertAddress(ctx context.Context, in *ConvertAddressRequest, opts ...grpc.CallOption) (*ConvertAddressResponse, error) {
	out := new(ConvertAddressResponse)
	err := c.cc.Invoke(ctx, ChainGatewayService_ConvertAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainGatewayServiceClient) BuildUnsignedTx(ctx context.Context, in *BuildUnsignedTxRequest, opts ...grpc.CallOption) (*BuildUnsignedTxResponse, error) {
	out := new(BuildUnsignedTxResponse)
	err := c.cc.Invoke(ctx, ChainGatewayService_BuildUnsignedTx_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainGatewayServiceClient) SendTx(ctx context.Context, in *SendTxRequest, opts ...grpc.CallOption) (*SendTxResponse, error) {
	out := new(SendTxResponse)
	err := c.cc.Invoke(ctx, ChainGatewayService_SendTx_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainGatewayServiceServer is the server API for ChainGatewayService service.
// All implementations must embed UnimplementedChainGatewayServiceServer
// for forward compatibility
type ChainGatewayServiceServer interface {
	ConvertAddress(context.Context, *ConvertAddressRequest) (*ConvertAddressResponse, error)
	BuildUnsignedTx(context.Context, *BuildUnsignedTxRequest) (*BuildUnsignedTxResponse, error)
	SendTx(context.Context, *SendTxRequest) (*SendTxResponse, error)
	mustEmbedUnimplementedChainGatewayServiceServer()
}

// UnimplementedChainGatewayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChainGatewayServiceServer struct {
}

func (UnimplementedChainGatewayServiceServer) ConvertAddress(context.Context, *ConvertAddressRequest) (*ConvertAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertAddress not implemented")
}
func (UnimplementedChainGatewayServiceServer) BuildUnsignedTx(context.Context, *BuildUnsignedTxRequest) (*BuildUnsignedTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildUnsignedTx not implemented")
}
func (UnimplementedChainGatewayServiceServer) SendTx(context.Context, *SendTxRequest) (*SendTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTx not implemented")
}
func (UnimplementedChainGatewayServiceServer) mustEmbedUnimplementedChainGatewayServiceServer() {}

// UnsafeChainGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainGatewayServiceServer will
// result in compilation errors.
type UnsafeChainGatewayServiceServer interface {
	mustEmbedUnimplementedChainGatewayServiceServer()
}

func RegisterChainGatewayServiceServer(s grpc.ServiceRegistrar, srv ChainGatewayServiceServer) {
	s.RegisterService(&ChainGatewayService_ServiceDesc, srv)
}

func _ChainGatewayService_ConvertAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainGatewayServiceServer).ConvertAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainGatewayService_ConvertAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainGatewayServiceServer).ConvertAddress(ctx, req.(*ConvertAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainGatewayService_BuildUnsignedTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildUnsignedTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainGatewayServiceServer).BuildUnsignedTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainGatewayService_BuildUnsignedTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainGatewayServiceServer).BuildUnsignedTx(ctx, req.(*BuildUnsignedTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainGatewayService_SendTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainGatewayServiceServer).SendTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainGatewayService_SendTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainGatewayServiceServer).SendTx(ctx, req.(*SendTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainGatewayService_ServiceDesc is the grpc.ServiceDesc for ChainGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.chaingateway.ChainGatewayService",
	HandlerType: (*ChainGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertAddress",
			Handler:    _ChainGatewayService_ConvertAddress_Handler,
		},
		{
			MethodName: "BuildUnsignedTx",
			Handler:    _ChainGatewayService_BuildUnsignedTx_Handler,
		},
		{
			MethodName: "SendTx",
			Handler:    _ChainGatewayService_SendTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/chaingateway.proto",
}
